gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to Pokémon Syndrome!\p"
	.string "My name is Dinklemeyer.\p"
	.string "But everyone calls me the Pokémon\n"
	.string "Scientist.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is the Pokémon Deoxys.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Deoxys has the entire Pokémon genome\n"
	.string "inside its own body.\p"
	.string "Modern science and technology however,\n"
	.string "has created a technique known as\l"
	.string "Polymerase Chain Reaction, or PCR.\p"
	.string "Using PCR, researchers have started\n"
	.string "to map and sequence Pokémon genomes.\p"
	.string "With this knowledge, Pokémon can be\n"
	.string "genetically engineered to be stronger.\p"
	.string "Some scientists use this new technique\n"
	.string "to create what they call perfect Pokémon.\p"
	.string "If their research continues, they will\n"
	.string "create a species of creature so strong\l"
	.string "that no one can stop them!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Pardon, who are you again?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to\n"
	.string "the town of Seluna.\l"
	.string "How exciting!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your first goal should be to\n"
	.string "obtain all 8 gym badges.\p"
	.string "The scientists have made research\n"
	.string "outposts near every major city.\l"
	.string "Please put a stop to them!\p"
	.string "Thank you for playing Pokémon Syndrome\n"
	.string "Please let me know of any bugs.\p"
	.string "$"
