gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to Pokémon Syndrome!\p"
	.string "My name is Dinklemeyer.\p"
	.string "But everyone calls me the Pokémon\n"
	.string "Scientist.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is the Pokémon Deoxys.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Deoxys has the entire Pokémon genome\n"
	.string "inside its own body.\p"
	.string "It was created when a space virus was hit\n"
	.string "by a laser beam deep in space.\p"
	.string "Using new technology, researchers have\n"
	.string "begun to try and replicate this virus.\p"
	.string "If they succeed, one of the worlds most\n"
	.string "dangerous pathogens may be released.\p"
	.string "So it falls to you to put a stop to the\n"
	.string "scientists and their research.\p"
	.string "If you are able to defeat them in a\n"
	.string "Pokémon battle, it might be enough to\l"
	.string "halt their research and stop them!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Pardon, who are you again?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to\n"
	.string "the town of Seluna.\l"
	.string "How exciting!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your first goal should be to\n"
	.string "obtain all 8 gym badges.\p"
	.string "The scientists have made research\n"
	.string "outposts near every major city.\l"
	.string "Please put a stop to them!\p"
	.string "Thank you for playing Pokémon Syndrome\n"
	.string "Please let me know of any bugs.\p"
	.string "$"
